name = "JolinPlutoCICD"
uuid = "41f5a839-9417-47e4-8d5e-d13fd1915f06"
authors = ["Stephan Sahm <stephan.sahm@jolin.io> and contributors"]
version = "0.1.5"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
